---
- hosts: all
  become: yes
  vars:
    password: pwd4IPynb
  tasks:

  - name: Install python and pip
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - python-dev
      - python-pip


  - name: Upgrade pip and setuptools
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
      - pip
      - setuptools


  - name: Install venv
    pip:
      name: virtualenv
      state: latest


  - name: Create app directory
    file:
      path: /vagrant/notebook
      state: directory


  - name: Create venv directory
    file:
      path: /home/vagrant/venv
      state: directory


  - name: Install packages
    pip:
      name: "{{ item }}"
      virtualenv: /home/vagrant/venv
      state: present
    with_items:
      - ipython
      - jupyter
      - pandas
      - matplotlib


  - name: Copy password script
    copy:
      src: ansible_files/encode_password.py
      dest: /home/vagrant/encode_password.py


  - name: Encode password
    shell: "/home/vagrant/venv/bin/python /home/vagrant/encode_password.py {{ password }}"
    register: encoded_password


  - name: Generate certificate and key for SSL
    shell: >
      openssl req -x509 -nodes -days 365 -newkey rsa:1024
      -keyout /home/vagrant/mykey.key
      -out /home/vagrant/mycert.pem
      -subj "/C=DE/ST=State/L=City/O=Org/OU=Unit/CN=Email"


  - name: Ensure .jupyter folder exists
    file: path=/home/vagrant/.jupyter state=directory


  - name: Template jupyter config file
    template:
      src: ansible_files/jupyter_notebook_config.py.j2
      dest: /home/vagrant/.jupyter/jupyter_notebook_config.py
